config/routes.rb
FunnyChat::Application.routes.draw do
  get "chat/main"

  controller :session do
    get '/session/new' => :new
    post '/session/login' => :login
    get '/session/logout' => :logout
  end

  controller :chat do
    get '/chat/main' => :main
    post '/chat/add_friend' => :add_friend
    get '/chat/remove_friend' => :remove_friend
  end

  resource :users

   root :to => 'session#new'

end

app/models/friend_list.rb
class FriendList < ActiveRecord::Base
  belongs_to :user
  attr_accessible :friend_id, :user_id
end

app/models/user.rb
include BCrypt

class User < ActiveRecord::Base
  has_many :friend_lists, :dependent => :destroy
  attr_accessible :full_name, :username, :email, :password, :password_confirmation
  attr_accessor :password

  validates :full_name, presence:true
  validates :username, :uniqueness => true, :length => { :minimum => 5}
  validates :email, presence:true, uniqueness:true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates_confirmation_of :password
  validates :password, :length => { :minimum => 7}

  before_save :encrypt_password

  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = Engine.generate_salt
      self.password_hash = Engine.hash_secret(password, password_salt)
    end
  end

  def user_friend_list
    a = Array.new
    i = 0
    self.friend_lists.each do |friend|
      a[i] = User.find_by_id(friend.friend_id)
      i+=1
    end
    return a
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected
  def authenticate_user
    unless session[:user]
      redirect_to session_new_path, :notice => "you need to login to access this page"
      return false
    else
      @current_user = User.find_by_username(session[:user])
      return true
    end
  end

  def save_login_state
     if session[:user]
       redirect_to chat_main_path
       return false
     else
       return true
     end
  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  before_filter :authenticate_user

  def main
    @friend_list = @current_user.user_friend_list
  end

  def add_friend
    friend = User.find_by_username(params[:username])
    respond_to do |format|
      if friend
        if @current_user.friend_lists.find_by_friend_id(friend.id)
          format.json { render :json => {:success => true, :status => "You added #{friend.username} already!"}}
        elsif friend.id == @current_user.id
          format.json { render :json => {:success => true, :status => "You cannot add yourself"}}
        else
          @current_user.friend_lists.create(:friend_id => friend.id)
          format.json { render :json => {:success => true, :friend => friend.username, :status => "Friend added"}}
        end
      else
        format.json { render :json => {:success => true, :status => "Friend not found"}}
      end
    end
  end

  def remove_friend
    friend = User.find_by_username(params[:username])
    respond_to do |format|
      if friend
        f_data = @current_user.friend_lists.find_by_friend_id(friend.id)
        if f_data
          f_data.destroy
          format.html { redirect_to chat_main_path, :notice => "Removed #{friend.username} from your friend list"}
        else
          format.html { redirect_to chat_main_path, :notice => "You don't have any friend with username #{friend.username}"}
        end
      else
         format.html { redirect_to chat_main_path, :notice => "Invalid username"}
      end
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  before_filter :save_login_state, :only => [:login, :new]
  before_filter :authenticate_user, :only => [:logout]

  def new
  end

  def login
    if User.authenticate(params[:username],params[:password])
       session[:user] = params[:username]
       redirect_to chat_main_path, :notice => "Login successfully"
    else
       redirect_to session_new_path, :notice => "Wrong username or password"
    end
  end

  def logout
    session[:user] = nil
    redirect_to session_new_path, :notice => "Logout successfully"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html {redirect_to session_new_url, :notice => "User was successfully created."}
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat/main.html.erb
<% content_for(:head) do %>
    <%= javascript_include_tag "chat/main" %>
<% end %>
<h1><%= notice %></h1>

<h1> main page</h1>

<%= text_field_tag "friend_username","username here" %>
<%= button_tag "Add Friend", :id => "add_friend_button" %>
<br/><br/>
<%= link_to "Log out", session_logout_path %>

<ul id="friend_list">
 <% @friend_list.each do |friend| %>
    <li><%= friend.username %>-------<%= link_to "remove", chat_remove_friend_path(:username => friend.username) %></li>
 <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FunnyChat</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body class="<%= "#{controller.controller_name}_#{controller.action_name}" %>">

<%= yield %>

</body>
</html>

app/views/session/login.html.erb
<h1>Session#login</h1>
<p>Find me in app/views/session/login.html.erb</p>

app/views/session/logout.html.erb
<h1>Session#logout</h1>
<p>Find me in app/views/session/logout.html.erb</p>

app/views/session/new.html.erb
<h1><%= notice %></h1>

<h1>Login Form</h1>

<%= form_tag(session_login_path, :method => :post ) do %>
  <%= label_tag 'username', 'Username: ' %>
  <%= text_field_tag 'username', nil, :placeholder => "Your Username" %>
  <br/> <br/>
  <%= label_tag 'password', 'Password: ' %>
  <%= password_field_tag 'password' %>
  <br/> <br/>
  <%= submit_tag 'Login' %>
  <br/> <br/>
<% end%>
<%= link_to 'Sign Up',new_users_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Full name</th>
    <th>Email</th>
    <th>Username</th>
    <th>Password</th>
    <th>Salt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.full_name %></td>
    <td><%= user.email %></td>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= user.salt %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', session_new_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Full name:</b>
  <%= @user.full_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Salt:</b>
  <%= @user.salt %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>